const GROUPS={"Положительная": ["Радость", "Восторг", "Счастье", "Ликование", "Воодушевление", "Вдохновение", "Удовольствие", "Умиротворение", "Нежность", "Любовь", "Благодарность", "Надежда", "Облегчение", "Гордость", "Уверенность", "Доверие", "Симпатия", "Забота", "Теплота", "Предвкушение"], "Негативная": ["Грусть", "Тоска", "Печаль", "Разочарование", "Обида", "Вина", "Стыд", "Отвращение", "Одиночество", "Беспомощность", "Усталость", "Апатия", "Безысходность"], "Напряжённая": ["Тревога", "Страх", "Паника", "Смущение", "Нервозность", "Подозрение", "Настороженность", "Растерянность", "Сомнение", "Нетерпение"], "Конфликтная": ["Злость", "Ярость", "Раздражение", "Возмущение", "Ревность", "Зависть", "Презрение", "Упрямство", "Мстительность", "Недоверие"], "Спокойная": ["Спокойствие", "Расслабленность", "Сосредоточенность", "Безмятежность", "Равнодушие", "Задумчивость", "Сдержанность"], "Социальная": ["Заинтересованность", "Вежливость", "Неловкость", "Сочувствие", "Восхищение", "Почтение", "Заискивание", "Снисходительность"], "Неожиданная": ["Удивление", "Шок", "Озадаченность", "Изумление", "Недоумение", "Ошеломление"], "Смешанная": ["Смех сквозь слёзы", "Тревожная радость", "Горькое облегчение", "Смущённая гордость", "Ностальгия", "Злорадство", "Ревнивая нежность"]}; const colors=['#3b3020','#3a2026','#202a3b','#3b2020','#20352f','#2d2740','#30303a','#3a2f20'];
let order=[],index=-1; const panel=document.getElementById('panel'),cat=document.getElementById('category'),emo=document.getElementById('emotion'),cnt=document.getElementById('counter');
function rebuild(){order=[];Object.entries(GROUPS).forEach(([g,es])=>es.forEach(e=>order.push({g,e})));order.sort(()=>Math.random()-.5)}
function beep(){if(!document.getElementById('sound').checked)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=440+Math.random()*220;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.12);o.start();o.stop(c.currentTime+.12)}catch(e){}}
function next(play=true){index++;if(index>=order.length){rebuild();index=0}const x=order[index];cat.textContent=x.g;emo.textContent=x.e;cnt.textContent=`${index+1} из ${order.length}`;document.body.style.background=colors[Object.keys(GROUPS).indexOf(x.g)%colors.length];if(play)beep()}
document.getElementById('next').onclick=()=>next(true);document.getElementById('settings').onclick=()=>panel.classList.add('open');document.getElementById('done').onclick=()=>panel.classList.remove('open');
document.getElementById('showCategory').onchange=e=>cat.style.opacity=e.target.checked?1:0;document.getElementById('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();
document.addEventListener('keydown',e=>{if(['Space','Enter','ArrowRight'].includes(e.code)||e.key==='Enter'){e.preventDefault();next(true)}});rebuild();next(false);

